<?php //if ($this->hasIdentity()): ?>

<?php //endif; ?>
<div class="full-body">
    <form class="form-signin" method="post" action="">
        <h2 class="form-signin-heading">Login</h2>
        <input name="username" type="text" class="form-control" placeholder="Username" required autofocus>
        <input name="password" type="password" class="form-control" placeholder="Password" required>
        <!--label class="checkbox">
          <input type="checkbox" value="remember-me"> Remember me
        </label-->
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
    </form>
</div>