<?php
$title = 'My Leave';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?>    <a class="btn btn-info pull-right btn-xs" href="/employee/apply">New Leave Application</a></h1>
<div >

</div>
<br/>
<table class="table">
    <tr>

        <th>Date</th>
        <th>Employee</th>
        <th>Leave Type</th>
        <th>Number of days</th>
        <th>Status</th>
        <th>Comments</th>

    </tr>
    <tr>
    </tr>
    <?php foreach($posts as $album) :?>
        <tr>
            <td><?php echo $this->escapeHtml($album->getDate()->format('Y-m-d'));?></td>
            <td><?php echo $this->escapeHtml($album->getEmployee());?></td>
            <td><?php echo $this->escapeHtml($album->getType());?></td>
            <td><?php echo $this->escapeHtml($album->getDays());?></td>
            <td><?php echo $this->escapeHtml($album->getStatus());?></td>
            <td><?php echo $this->escapeHtml($album->getComments());?></td>

        </tr>
    <?php endforeach; ?>
</table>